# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  back-end:
    build:
      context: .
    image: small-domain-chatbot-back-end
    environment:
      - ollama_host=${ollama_host}
      - ollama_port=${ollama_port}
      - llm_model_name=${llm_model_name}
    ports:
      - 5601:5601
    volumes:
      - back-end-logs:/app/_log
    depends_on:
      - ollama
  
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    environment:
      - llm_model_name=${llm_model_name}
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: ["/bin/bash", "-c", "\
      ollama serve && \
      ollama pull $${llm_model_name} && \
      wait"]

  front-end:
    build:
      context: ./react_frontend
    image: small-domain-chatbot-front-end
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000
    depends_on:
      - back-end


volumes:
  ollama-data:
  back-end-logs:
